version: '3.7'

volumes:
  postgres:

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=workshop-admin
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres:/var/lib/postgresql
      - postgres:/var/log/postgresql
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=root@admin.com
     - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"