import { DataSource } from 'typeorm';
import { ServiceType } from '../modules/service_type/entities/service_type.entity';

export async function seedServiceTypes(dataSource: DataSource): Promise<void> {
  const services = [
    { name: 'Cambio de Aceite', description: 'Reemplazar el aceite del motor y el filtro', recommended_interval_in_days: 'Cada 5000 km', estimated_cost: 500.00 },
    { name: 'Inspección de Frenos', description: 'Inspeccionar pastillas, discos y líquido de frenos', recommended_interval_in_day: 'Cada 10000 km', estimated_cost: 100.00 },
    { name: 'Cambio de Pastillas de Freno', description: 'Reemplazar las pastillas de freno desgastadas', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 1500.00 },
    { name: 'Rotación de Llantas', description: 'Rotar las llantas para un desgaste uniforme', recommended_interval_in_day: 'Cada 7500 km', estimated_cost: 300.00 },
    { name: 'Cambio de Llantas', description: 'Reemplazar llantas desgastadas', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 8000.00 },
    { name: 'Alineación de Llantas', description: 'Ajustar la alineación de las llantas', recommended_interval_in_day: 'Cada 12000 km', estimated_cost: 1200.00 },
    { name: 'Cambio de Batería', description: 'Reemplazar la batería del coche', recommended_interval_in_day: 'Cada 4 años', estimated_cost: 1800.00 },
    { name: 'Cambio de Bujías', description: 'Reemplazar bujías desgastadas', recommended_interval_in_day: 'Cada 30000 km', estimated_cost: 600.00 },
    { name: 'Cambio de Filtro de Aire', description: 'Reemplazar el filtro de aire', recommended_interval_in_day: 'Cada 15000 km', estimated_cost: 200.00 },
    { name: 'Cambio de Filtro de Combustible', description: 'Reemplazar el filtro de combustible', recommended_interval_in_day: 'Cada 30000 km', estimated_cost: 400.00 },
    { name: 'Cambio de Aceite de Transmisión', description: 'Cambiar el aceite de la transmisión', recommended_interval_in_day: 'Cada 60000 km', estimated_cost: 1500.00 },
    { name: 'Cambio de Anticongelante', description: 'Cambiar y reemplazar el anticongelante', recommended_interval_in_day: 'Cada 50000 km', estimated_cost: 1000.00 },
    { name: 'Cambio de Radiador', description: 'Reemplazar el radiador', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 4500.00 },
    { name: 'Recarga del Aire Acondicionado', description: 'Recargar el sistema de aire acondicionado', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 1500.00 },
    { name: 'Reparación del Aire Acondicionado', description: 'Reparar el sistema de aire acondicionado', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 3000.00 },
    { name: 'Cambio de Correa (Distribución, Serpentina)', description: 'Reemplazar las correas desgastadas', recommended_interval_in_day: 'Cada 60000 km', estimated_cost: 2500.00 },
    { name: 'Cambio de Mangueras', description: 'Reemplazar las mangueras desgastadas', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 1000.00 },
    { name: 'Cambio de Limpiaparabrisas', description: 'Reemplazar los limpiaparabrisas', recommended_interval_in_day: 'Anualmente', estimated_cost: 300.00 },
    { name: 'Cambio de Foco del Faro', description: 'Reemplazar los focos del faro', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 200.00 },
    { name: 'Cambio de Foco de la Calavera', description: 'Reemplazar los focos de la calavera', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 200.00 },
    { name: 'Reparación/Reemplazo del Sistema de Escape', description: 'Reparar o reemplazar el sistema de escape', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 4000.00 },
    { name: 'Cambio de Silenciador', description: 'Reemplazar el silenciador', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 1500.00 },
    { name: 'Inspección de Suspensión', description: 'Inspeccionar el sistema de suspensión', recommended_interval_in_day: 'Cada 30000 km', estimated_cost: 600.00 },
    { name: 'Cambio de Amortiguadores', description: 'Reemplazar los amortiguadores', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 2500.00 },
    { name: 'Cambio de Struts', description: 'Reemplazar los struts', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 3000.00 },
    { name: 'Cambio de Junta Homocinética', description: 'Reemplazar las juntas homocinéticas', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 1500.00 },
    { name: 'Cambio del Eje de Transmisión', description: 'Reemplazar el eje de transmisión', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 4000.00 },
    { name: 'Cambio de Aceite del Diferencial', description: 'Cambiar el aceite del diferencial', recommended_interval_in_day: 'Cada 30000 km', estimated_cost: 700.00 },
    { name: 'Cambio de Aceite de la Dirección Hidráulica', description: 'Cambiar el aceite de la dirección hidráulica', recommended_interval_in_day: 'Cada 50000 km', estimated_cost: 600.00 },
    { name: 'Cambio de Líquido de Frenos', description: 'Cambiar y reemplazar el líquido de frenos', recommended_interval_in_day: 'Cada 30000 km', estimated_cost: 800.00 },
    { name: 'Afinación del Motor', description: 'Mantenimiento completo del motor', recommended_interval_in_day: 'Cada 30000 km', estimated_cost: 3000.00 },
    { name: 'Cambio de Rodamientos de Rueda', description: 'Reemplazar los rodamientos de rueda', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 1500.00 },
    { name: 'Limpieza Interior', description: 'Limpieza detallada del interior del vehículo', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 1000.00 },
    { name: 'Lavado y Encerado Exterior', description: 'Lavado y encerado del exterior del vehículo', recommended_interval_in_day: 'Mensual', estimated_cost: 300.00 },
    { name: 'Retocar Pintura', description: 'Reparar pequeños daños en la pintura', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 1000.00 },
    { name: 'Eliminación de Abolladuras', description: 'Eliminar pequeñas abolladuras', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 2000.00 },
    { name: 'Reparación de Tapicería', description: 'Reparar la tapicería del vehículo', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 1500.00 },
    { name: 'Polarizado de Ventanas', description: 'Aplicar polarizado a las ventanas del vehículo', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 2000.00 },
    { name: 'Cambio del Regulador de Ventana', description: 'Reemplazar el regulador de la ventana', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 1500.00 },
    { name: 'Reparación de Cerradura de Puerta', description: 'Reparar cerraduras de puertas', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 1000.00 },
    { name: 'Cambio de Parabrisas', description: 'Reemplazar el parabrisas', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 2500.00 },
    { name: 'Limpieza del Sistema de Combustible', description: 'Limpiar el sistema de combustible', recommended_interval_in_day: 'Cada 30000 km', estimated_cost: 1000.00 },
    { name: 'Reparación del Sistema de Emisiones', description: 'Reparar el sistema de emisiones', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 2000.00 },
    { name: 'Cambio del Sensor de Oxígeno', description: 'Reemplazar el sensor de oxígeno', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 1500.00 },
    { name: 'Cambio del Catalizador', description: 'Reemplazar el catalizador', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 5000.00 },
    { name: 'Cambio de la Válvula EGR', description: 'Reemplazar la válvula EGR', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 2000.00 },
    { name: 'Limpieza del Cuerpo del Acelerador', description: 'Limpiar el cuerpo del acelerador', recommended_interval_in_day: 'Cada 30000 km', estimated_cost: 1000.00 },
    { name: 'Limpieza de Inyectores de Combustible', description: 'Limpiar los inyectores de combustible', recommended_interval_in_day: 'Cada 30000 km', estimated_cost: 1500.00 },
    { name: 'Servicio al Turbo', description: 'Servicio al turbo', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 3000.00 },
    { name: 'Servicio al Supercargador', description: 'Servicio al supercargador', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 3000.00 },
    { name: 'Cambio de Cadena de Distribución', description: 'Reemplazar la cadena de distribución', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 6000.00 },
    { name: 'Cambio de Correa de Distribución', description: 'Reemplazar la correa de distribución', recommended_interval_in_day: 'Cada 60000 km', estimated_cost: 5000.00 },
    { name: 'Cambio de Bomba de Agua', description: 'Reemplazar la bomba de agua', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 4000.00 },
    { name: 'Reparación Completa del Motor', description: 'Reparación completa del motor', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 25000.00 },
    { name: 'Cambio de Soportes del Motor', description: 'Reemplazar los soportes del motor', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 3000.00 },
    { name: 'Reparación/Reemplazo de la Transmisión', description: 'Reparar o reemplazar la transmisión', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 25000.00 },
    { name: 'Cambio del Embrague', description: 'Reemplazar el embrague', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 8000.00 },
    { name: 'Reparación/Reemplazo del Diferencial', description: 'Reparar o reemplazar el diferencial', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 15000.00 },
    { name: 'Cambio del Eje', description: 'Reemplazar el eje', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 4000.00 },
    { name: 'Cambio del Radiador de Calefacción', description: 'Reemplazar el radiador de calefacción', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 6000.00 },
    { name: 'Cambio del Motor del Ventilador', description: 'Reemplazar el motor del ventilador', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 3000.00 },
    { name: 'Reparación del Tablero de Instrumentos', description: 'Reparar el tablero de instrumentos', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 2500.00 },
    { name: 'Cambio de Sensores (Varios)', description: 'Reemplazar varios sensores', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 1500.00 },
    { name: 'Cambio de Cinturón de Seguridad', description: 'Reemplazar cinturones de seguridad', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 1000.00 },
    { name: 'Servicio del Sistema de Airbags', description: 'Servicio del sistema de airbags', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 3000.00 },
    { name: 'Ajuste del Freno de Mano', description: 'Ajustar el freno de mano', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 500.00 },
    { name: 'Reparación del Control de Crucero', description: 'Reparar el control de crucero', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 2000.00 },
    { name: 'Instalación de Encendido Remoto', description: 'Instalar encendido remoto', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 3000.00 },
    { name: 'Instalación del Sistema de Audio', description: 'Instalar sistema de audio', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 2000.00 },
    { name: 'Instalación de Sistema de Navegación GPS', description: 'Instalar sistema de navegación GPS', recommended_interval_in_day: 'Según sea necesario', estimated_cost: 2500.00 }
  ];

  await dataSource
    .createQueryBuilder()
    .insert()
    .into(ServiceType)
    .values(services)
    .execute();
}
