import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateSnakeToCamelCase1724440675203 implements MigrationInterface {
    name = 'UpdateSnakeToCamelCase1724440675203'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "person" ("id" SERIAL NOT NULL, "firstName" character varying NOT NULL, "secondName" character varying, "lastName" character varying NOT NULL, "age" integer, "imageUrl" character varying, "phoneNumber" character varying, CONSTRAINT "UQ_8e40da59e944ec667758f99f236" UNIQUE ("imageUrl"), CONSTRAINT "UQ_538b428794bb0c006fb08fc2026" UNIQUE ("phoneNumber"), CONSTRAINT "PK_5fdaf670315c4b7e70cce85daa3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employee" ("id" SERIAL NOT NULL, "firstName" character varying NOT NULL, "secondName" character varying, "lastName" character varying NOT NULL, "age" integer, "imageUrl" character varying, "phoneNumber" character varying, "salary" integer NOT NULL, CONSTRAINT "UQ_0305e35f857145f136de86cffcf" UNIQUE ("imageUrl"), CONSTRAINT "UQ_b16a62b0eb49a67425c9a6bca18" UNIQUE ("phoneNumber"), CONSTRAINT "PK_3c2bc72f03fd5abbbc5ac169498" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "service_type" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "frequency_in_days" integer NOT NULL, CONSTRAINT "PK_0a11a8d444eff1346826caed987" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "service_order" ("id" SERIAL NOT NULL, "totalPrice" numeric NOT NULL, CONSTRAINT "PK_b01a59b48a0dfbd84dd8221364a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "service_order_service" ("id" SERIAL NOT NULL, "servicePriceAtOrder" numeric NOT NULL, "serviceId" integer, "serviceOrderId" integer, CONSTRAINT "PK_32a8a62683ded69aac34b40f526" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "service" ("id" SERIAL NOT NULL, "price" numeric NOT NULL, "date" character varying NOT NULL, "typeId" integer, CONSTRAINT "PK_85a21558c006647cd76fdce044b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "service_spare_part" ("id" SERIAL NOT NULL, "priceAtOrder" numeric NOT NULL, "serviceId" integer, "sparePartId" integer, CONSTRAINT "PK_c1cc94911e02b2bdec41ba84259" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "spare_part" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "brand" character varying NOT NULL, "description" character varying NOT NULL, CONSTRAINT "PK_10e3c1ce9b357df381cc81d1654" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vehicle_spare_part" ("id" SERIAL NOT NULL, "sparePartId" integer, CONSTRAINT "PK_a777d0e8f9d308790b79ae11130" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "second_name"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_61c5f10be5cc6bd1dcbfa35862a"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_01eea41349b6c9275aec646eee0"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "phone_number"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "user_type"`);
        await queryRunner.query(`DROP TYPE "public"."user_user_type_enum"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "days_to_work"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "employee_since"`);
        await queryRunner.query(`ALTER TABLE "customer_vehicle" DROP CONSTRAINT "UQ_3039619e264649a53807dd5f6e4"`);
        await queryRunner.query(`ALTER TABLE "customer_vehicle" DROP COLUMN "license_plate"`);
        await queryRunner.query(`ALTER TABLE "customer_vehicle" DROP COLUMN "vehicle_model_id"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "second_name"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "UQ_be68bb33b8121ed4c57104be50d"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "UQ_998bb43a16f512608c017301523"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "phone_number"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "firstName" character varying`);
        await queryRunner.query(`ALTER TABLE "user" ADD "secondName" character varying`);
        await queryRunner.query(`ALTER TABLE "user" ADD "lastName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD "imageUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_7702daaa8e3b4f2d0b32601c9b2" UNIQUE ("imageUrl")`);
        await queryRunner.query(`ALTER TABLE "user" ADD "phoneNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_f2578043e491921209f5dadd080" UNIQUE ("phoneNumber")`);
        await queryRunner.query(`CREATE TYPE "public"."user_usertype_enum" AS ENUM('admin', 'mechanic')`);
        await queryRunner.query(`ALTER TABLE "user" ADD "userType" "public"."user_usertype_enum" NOT NULL DEFAULT 'mechanic'`);
        await queryRunner.query(`ALTER TABLE "user" ADD "daysToWork" text`);
        await queryRunner.query(`ALTER TABLE "user" ADD "employeeSince" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer_vehicle" ADD "licensePlate" character varying`);
        await queryRunner.query(`ALTER TABLE "customer_vehicle" ADD CONSTRAINT "UQ_6efb20db0a96aab90fc3c5dfb8a" UNIQUE ("licensePlate")`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "firstName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "secondName" character varying`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "lastName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "imageUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "UQ_519a193a0d3017818a6ab01570f" UNIQUE ("imageUrl")`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "phoneNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "UQ_2e64383bae8871598afb8b73f0d" UNIQUE ("phoneNumber")`);
        await queryRunner.query(`ALTER TABLE "customer_vehicle" DROP CONSTRAINT "FK_332138c0c8a1f7bbd4a9c04d67e"`);
        await queryRunner.query(`ALTER TABLE "customer_vehicle" ALTER COLUMN "vehicleModelId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer_vehicle" ALTER COLUMN "vehicleModelId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "service_order_service" ADD CONSTRAINT "FK_af0b56e1bc6d790eb3ef534ffa9" FOREIGN KEY ("serviceId") REFERENCES "service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_order_service" ADD CONSTRAINT "FK_7776d812c6b6b1a6e015aa2682a" FOREIGN KEY ("serviceOrderId") REFERENCES "service_order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service" ADD CONSTRAINT "FK_9890172914c5b65b012647d2295" FOREIGN KEY ("typeId") REFERENCES "service_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_spare_part" ADD CONSTRAINT "FK_96b5abe86813221f23ed4506457" FOREIGN KEY ("serviceId") REFERENCES "service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_spare_part" ADD CONSTRAINT "FK_75be3555ef648159e2a0cfe32b3" FOREIGN KEY ("sparePartId") REFERENCES "spare_part"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_spare_part" ADD CONSTRAINT "FK_b6207e19eeabca700ee1c3f9677" FOREIGN KEY ("sparePartId") REFERENCES "spare_part"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_vehicle" ADD CONSTRAINT "FK_332138c0c8a1f7bbd4a9c04d67e" FOREIGN KEY ("vehicleModelId") REFERENCES "vehicle_model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "customer_vehicle" DROP CONSTRAINT "FK_332138c0c8a1f7bbd4a9c04d67e"`);
        await queryRunner.query(`ALTER TABLE "vehicle_spare_part" DROP CONSTRAINT "FK_b6207e19eeabca700ee1c3f9677"`);
        await queryRunner.query(`ALTER TABLE "service_spare_part" DROP CONSTRAINT "FK_75be3555ef648159e2a0cfe32b3"`);
        await queryRunner.query(`ALTER TABLE "service_spare_part" DROP CONSTRAINT "FK_96b5abe86813221f23ed4506457"`);
        await queryRunner.query(`ALTER TABLE "service" DROP CONSTRAINT "FK_9890172914c5b65b012647d2295"`);
        await queryRunner.query(`ALTER TABLE "service_order_service" DROP CONSTRAINT "FK_7776d812c6b6b1a6e015aa2682a"`);
        await queryRunner.query(`ALTER TABLE "service_order_service" DROP CONSTRAINT "FK_af0b56e1bc6d790eb3ef534ffa9"`);
        await queryRunner.query(`ALTER TABLE "customer_vehicle" ALTER COLUMN "vehicleModelId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer_vehicle" ALTER COLUMN "vehicleModelId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer_vehicle" ADD CONSTRAINT "FK_332138c0c8a1f7bbd4a9c04d67e" FOREIGN KEY ("vehicleModelId") REFERENCES "vehicle_model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "UQ_2e64383bae8871598afb8b73f0d"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "phoneNumber"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "UQ_519a193a0d3017818a6ab01570f"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "imageUrl"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "secondName"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "customer_vehicle" DROP CONSTRAINT "UQ_6efb20db0a96aab90fc3c5dfb8a"`);
        await queryRunner.query(`ALTER TABLE "customer_vehicle" DROP COLUMN "licensePlate"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "employeeSince"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "daysToWork"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "userType"`);
        await queryRunner.query(`DROP TYPE "public"."user_usertype_enum"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_f2578043e491921209f5dadd080"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "phoneNumber"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_7702daaa8e3b4f2d0b32601c9b2"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "imageUrl"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "secondName"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "phone_number" character varying`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "UQ_998bb43a16f512608c017301523" UNIQUE ("phone_number")`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "image_url" character varying`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "UQ_be68bb33b8121ed4c57104be50d" UNIQUE ("image_url")`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "last_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "second_name" character varying`);
        await queryRunner.query(`ALTER TABLE "customer" ADD "first_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer_vehicle" ADD "vehicle_model_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customer_vehicle" ADD "license_plate" character varying`);
        await queryRunner.query(`ALTER TABLE "customer_vehicle" ADD CONSTRAINT "UQ_3039619e264649a53807dd5f6e4" UNIQUE ("license_plate")`);
        await queryRunner.query(`ALTER TABLE "user" ADD "employee_since" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD "days_to_work" text`);
        await queryRunner.query(`CREATE TYPE "public"."user_user_type_enum" AS ENUM('admin', 'mechanic')`);
        await queryRunner.query(`ALTER TABLE "user" ADD "user_type" "public"."user_user_type_enum" NOT NULL DEFAULT 'mechanic'`);
        await queryRunner.query(`ALTER TABLE "user" ADD "phone_number" character varying`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_01eea41349b6c9275aec646eee0" UNIQUE ("phone_number")`);
        await queryRunner.query(`ALTER TABLE "user" ADD "image_url" character varying`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_61c5f10be5cc6bd1dcbfa35862a" UNIQUE ("image_url")`);
        await queryRunner.query(`ALTER TABLE "user" ADD "last_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD "second_name" character varying`);
        await queryRunner.query(`ALTER TABLE "user" ADD "first_name" character varying NOT NULL`);
        await queryRunner.query(`DROP TABLE "vehicle_spare_part"`);
        await queryRunner.query(`DROP TABLE "spare_part"`);
        await queryRunner.query(`DROP TABLE "service_spare_part"`);
        await queryRunner.query(`DROP TABLE "service"`);
        await queryRunner.query(`DROP TABLE "service_order_service"`);
        await queryRunner.query(`DROP TABLE "service_order"`);
        await queryRunner.query(`DROP TABLE "service_type"`);
        await queryRunner.query(`DROP TABLE "employee"`);
        await queryRunner.query(`DROP TABLE "person"`);
    }

}
